name: BuildOnPush

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        xcodebuild -project sib-lite.xcodeproj -scheme sib-lite -configuration Debug -derivedDataPath $HOME/sib-lite build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
        
